basePath: /
definitions:
  entities.Acommodation:
    properties:
      Id:
        type: integer
      checkIn:
        type: string
      checkOut:
        type: string
      garage:
        type: boolean
      price:
        type: number
      roomId:
        type: integer
      userId:
        type: integer
    type: object
  entities.Error:
    properties:
      errorMessage:
        type: string
    type: object
  entities.User:
    properties:
      document:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /reservation:
    get:
      consumes:
      - application/json
      description: Get a list of all Reservation
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Acommodation'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: List all Reservation
      tags:
      - Reservation
    post:
      consumes:
      - application/json
      description: Register a new reservation for a user in a room
      parameters:
      - description: reservation info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entities.Acommodation'
      produces:
      - application/json
      responses:
        "201":
          description: Reservation created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Register Reservation
      tags:
      - Reservation
  /users:
    get:
      consumes:
      - application/json
      description: List all users
      parameters:
      - description: User Name
        in: query
        name: name
        type: string
      - description: User Document
        in: query
        name: document
        type: string
      - description: User Phone
        in: query
        name: phone
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: List Users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: user info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      produces:
      - application/json
      responses:
        "201":
          description: User created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Register User
      tags:
      - Users
  /users/{id}:
    delete:
      description: Delete a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: User deleted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Delete User
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: user info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      produces:
      - application/json
      responses:
        "200":
          description: User updated
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Update User
      tags:
      - Users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
